[config]
schemaVersion = "0.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./BepInEx"
target = "./BepInEx"

[package]
namespace = "femboytv"
name = "FemboyTV_Posters"
versionNumber = "3.0.0"
description = "Poster mods for the best femboy modpack :3"
websiteUrl = "https://femboy.tv"
containsNsfwContent = false

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "bepinex", "modpacks", ]

[package.dependencies]
# Poster deps
femboytv-LethalPosters = "1.2.0"
femboytv-LethalPaintings = "1.2.0"
# Poster packs
femboytv-BoykisserPosters = "1.2.1"
femboytv-DeepRockPosters = "1.2.1"
femboytv-FemboyTVPosters = "1.2.0"
femboytv-FemboysAndFirearms = "1.2.1"
femboytv-LethalGosling = "1.0.1"
femboytv-LethalReynolds = "1.2.0"
femboytv-XeniaPosters = "1.2.1"